// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddPhone(arg1:string,arg2:string):Promise<main.AddPhoneResult>;

export function DeleteClipPermanently(arg1:string,arg2:string):Promise<void>;

export function EmptyTrash():Promise<number>;

export function GetPhoneDetail(arg1:string):Promise<main.PhoneDetailView>;

export function IsQuitting():Promise<boolean>;

export function ListClips(arg1:string):Promise<Array<main.ClipView>>;

export function ListPhones():Promise<Array<main.PhoneView>>;

export function ListTrash():Promise<Array<main.ClipView>>;

export function ParseInviteURL(arg1:string):Promise<main.ParsedInvite>;

export function RequestQuit():Promise<void>;

export function RestoreClip(arg1:string,arg2:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function TrashClip(arg1:string,arg2:string):Promise<void>;
