// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPhone(arg1, arg2) {
  return window['go']['main']['App']['AddPhone'](arg1, arg2);
}

export function DeleteClipPermanently(arg1, arg2) {
  return window['go']['main']['App']['DeleteClipPermanently'](arg1, arg2);
}

export function EmptyTrash() {
  return window['go']['main']['App']['EmptyTrash']();
}

export function GetPhoneDetail(arg1) {
  return window['go']['main']['App']['GetPhoneDetail'](arg1);
}

export function IsQuitting() {
  return window['go']['main']['App']['IsQuitting']();
}

export function ListClips(arg1) {
  return window['go']['main']['App']['ListClips'](arg1);
}

export function ListPhones() {
  return window['go']['main']['App']['ListPhones']();
}

export function ListTrash() {
  return window['go']['main']['App']['ListTrash']();
}

export function ParseInviteURL(arg1) {
  return window['go']['main']['App']['ParseInviteURL'](arg1);
}

export function RequestQuit() {
  return window['go']['main']['App']['RequestQuit']();
}

export function RestoreClip(arg1, arg2) {
  return window['go']['main']['App']['RestoreClip'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function TrashClip(arg1, arg2) {
  return window['go']['main']['App']['TrashClip'](arg1, arg2);
}
