// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calibration.sql

package queries

import (
	"context"
)

const getCalibration = `-- name: GetCalibration :one
SELECT manufacturer_model, source_phone_id, calibrated_at_ms, result_json
FROM calibration WHERE manufacturer_model = ?
`

func (q *Queries) GetCalibration(ctx context.Context, manufacturerModel string) (Calibration, error) {
	row := q.db.QueryRowContext(ctx, getCalibration, manufacturerModel)
	var i Calibration
	err := row.Scan(
		&i.ManufacturerModel,
		&i.SourcePhoneID,
		&i.CalibratedAtMs,
		&i.ResultJson,
	)
	return i, err
}

const upsertCalibration = `-- name: UpsertCalibration :exec
INSERT INTO calibration (manufacturer_model, source_phone_id, calibrated_at_ms, result_json)
VALUES (?, ?, ?, ?)
ON CONFLICT(manufacturer_model) DO UPDATE SET
    source_phone_id  = excluded.source_phone_id,
    calibrated_at_ms = excluded.calibrated_at_ms,
    result_json      = excluded.result_json
`

type UpsertCalibrationParams struct {
	ManufacturerModel string
	SourcePhoneID     string
	CalibratedAtMs    int64
	ResultJson        string
}

func (q *Queries) UpsertCalibration(ctx context.Context, arg UpsertCalibrationParams) error {
	_, err := q.db.ExecContext(ctx, upsertCalibration,
		arg.ManufacturerModel,
		arg.SourcePhoneID,
		arg.CalibratedAtMs,
		arg.ResultJson,
	)
	return err
}
