// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clips.sql

package queries

import (
	"context"
)

const clipExists = `-- name: ClipExists :one
SELECT COUNT(1) FROM clips WHERE phone_id = ? AND filename = ?
`

type ClipExistsParams struct {
	PhoneID  string
	Filename string
}

func (q *Queries) ClipExists(ctx context.Context, arg ClipExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, clipExists, arg.PhoneID, arg.Filename)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const diskUsageBytes = `-- name: DiskUsageBytes :one
SELECT CAST(COALESCE(SUM(size_bytes), 0) AS INTEGER) FROM clips
WHERE state IN ('active', 'trashed')
  AND (CAST(?1 AS TEXT) = '' OR phone_id = ?1)
`

// sqlc.arg(phone_id) = "" means every phone; see ListClips above.
func (q *Queries) DiskUsageBytes(ctx context.Context, phoneID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, diskUsageBytes, phoneID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getClip = `-- name: GetClip :one
SELECT phone_id, filename, state, local_path, thumbnail_path, created_at_ms, duration_ms, size_bytes, width, height
FROM clips WHERE phone_id = ? AND filename = ?
`

type GetClipParams struct {
	PhoneID  string
	Filename string
}

func (q *Queries) GetClip(ctx context.Context, arg GetClipParams) (Clip, error) {
	row := q.db.QueryRowContext(ctx, getClip, arg.PhoneID, arg.Filename)
	var i Clip
	err := row.Scan(
		&i.PhoneID,
		&i.Filename,
		&i.State,
		&i.LocalPath,
		&i.ThumbnailPath,
		&i.CreatedAtMs,
		&i.DurationMs,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
	)
	return i, err
}

const listClips = `-- name: ListClips :many
SELECT phone_id, filename, state, local_path, thumbnail_path, created_at_ms, duration_ms, size_bytes, width, height
FROM clips
WHERE (CAST(?1 AS TEXT) = '' OR phone_id = ?1)
  AND (CAST(?2 AS TEXT) = '' OR state = ?2)
ORDER BY created_at_ms DESC
`

type ListClipsParams struct {
	PhoneID string
	State   string
}

// sqlc.arg(phone_id) = "" means every phone, sqlc.arg(state) = "" means
// every state - the sentinel-OR trick keeps this one static query doing
// the work of what would otherwise be up to four hand-built variants.
func (q *Queries) ListClips(ctx context.Context, arg ListClipsParams) ([]Clip, error) {
	rows, err := q.db.QueryContext(ctx, listClips, arg.PhoneID, arg.State)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Clip{}
	for rows.Next() {
		var i Clip
		if err := rows.Scan(
			&i.PhoneID,
			&i.Filename,
			&i.State,
			&i.LocalPath,
			&i.ThumbnailPath,
			&i.CreatedAtMs,
			&i.DurationMs,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setClipState = `-- name: SetClipState :exec
UPDATE clips SET state = ? WHERE phone_id = ? AND filename = ?
`

type SetClipStateParams struct {
	State    string
	PhoneID  string
	Filename string
}

func (q *Queries) SetClipState(ctx context.Context, arg SetClipStateParams) error {
	_, err := q.db.ExecContext(ctx, setClipState, arg.State, arg.PhoneID, arg.Filename)
	return err
}

const upsertClip = `-- name: UpsertClip :exec
INSERT INTO clips (phone_id, filename, state, local_path, thumbnail_path, created_at_ms, duration_ms, size_bytes, width, height)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(phone_id, filename) DO NOTHING
`

type UpsertClipParams struct {
	PhoneID       string
	Filename      string
	State         string
	LocalPath     string
	ThumbnailPath string
	CreatedAtMs   int64
	DurationMs    int64
	SizeBytes     int64
	Width         int64
	Height        int64
}

func (q *Queries) UpsertClip(ctx context.Context, arg UpsertClipParams) error {
	_, err := q.db.ExecContext(ctx, upsertClip,
		arg.PhoneID,
		arg.Filename,
		arg.State,
		arg.LocalPath,
		arg.ThumbnailPath,
		arg.CreatedAtMs,
		arg.DurationMs,
		arg.SizeBytes,
		arg.Width,
		arg.Height,
	)
	return err
}
