// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clips.sql

package queries

import (
	"context"
)

const diskUsageBytes = `-- name: DiskUsageBytes :one
SELECT CAST(COALESCE(SUM(s.size_bytes), 0) AS INTEGER)
FROM segments s
JOIN clips c ON c.id = s.clip_id
WHERE c.state IN ('active', 'trashed')
  AND (CAST(?1 AS TEXT) = '' OR c.phone_id = ?1)
`

// sqlc.arg(phone_id) = "" means every phone. Disk usage is the on-disk bytes of
// segments belonging to non-purged clips (purged clips have had their files
// removed).
func (q *Queries) DiskUsageBytes(ctx context.Context, phoneID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, diskUsageBytes, phoneID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const extendClip = `-- name: ExtendClip :exec
UPDATE clips
SET ended_at_ms = ?, segment_count = segment_count + 1, size_bytes = size_bytes + ?
WHERE id = ?
`

type ExtendClipParams struct {
	EndedAtMs int64
	SizeBytes int64
	ID        string
}

func (q *Queries) ExtendClip(ctx context.Context, arg ExtendClipParams) error {
	_, err := q.db.ExecContext(ctx, extendClip, arg.EndedAtMs, arg.SizeBytes, arg.ID)
	return err
}

const getClip = `-- name: GetClip :one
SELECT id, phone_id, started_at_ms, ended_at_ms, segment_count, size_bytes, state, created_at_ms
FROM clips WHERE phone_id = ? AND id = ?
`

type GetClipParams struct {
	PhoneID string
	ID      string
}

func (q *Queries) GetClip(ctx context.Context, arg GetClipParams) (Clip, error) {
	row := q.db.QueryRowContext(ctx, getClip, arg.PhoneID, arg.ID)
	var i Clip
	err := row.Scan(
		&i.ID,
		&i.PhoneID,
		&i.StartedAtMs,
		&i.EndedAtMs,
		&i.SegmentCount,
		&i.SizeBytes,
		&i.State,
		&i.CreatedAtMs,
	)
	return i, err
}

const getOpenClip = `-- name: GetOpenClip :one
SELECT id, phone_id, started_at_ms, ended_at_ms, segment_count, size_bytes, state, created_at_ms
FROM clips
WHERE phone_id = ? AND state = 'active'
ORDER BY ended_at_ms DESC LIMIT 1
`

func (q *Queries) GetOpenClip(ctx context.Context, phoneID string) (Clip, error) {
	row := q.db.QueryRowContext(ctx, getOpenClip, phoneID)
	var i Clip
	err := row.Scan(
		&i.ID,
		&i.PhoneID,
		&i.StartedAtMs,
		&i.EndedAtMs,
		&i.SegmentCount,
		&i.SizeBytes,
		&i.State,
		&i.CreatedAtMs,
	)
	return i, err
}

const insertClip = `-- name: InsertClip :exec
INSERT INTO clips (id, phone_id, started_at_ms, ended_at_ms, segment_count, size_bytes, state, created_at_ms)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertClipParams struct {
	ID           string
	PhoneID      string
	StartedAtMs  int64
	EndedAtMs    int64
	SegmentCount int64
	SizeBytes    int64
	State        string
	CreatedAtMs  int64
}

func (q *Queries) InsertClip(ctx context.Context, arg InsertClipParams) error {
	_, err := q.db.ExecContext(ctx, insertClip,
		arg.ID,
		arg.PhoneID,
		arg.StartedAtMs,
		arg.EndedAtMs,
		arg.SegmentCount,
		arg.SizeBytes,
		arg.State,
		arg.CreatedAtMs,
	)
	return err
}

const listClips = `-- name: ListClips :many
SELECT id, phone_id, started_at_ms, ended_at_ms, segment_count, size_bytes, state, created_at_ms
FROM clips
WHERE (CAST(?1 AS TEXT) = '' OR phone_id = ?1)
  AND (CAST(?2 AS TEXT) = '' OR state = ?2)
ORDER BY started_at_ms DESC
`

type ListClipsParams struct {
	PhoneID string
	State   string
}

// sqlc.arg(phone_id) = "" means every phone, sqlc.arg(state) = "" means every
// state - the sentinel-OR trick keeps this one static query doing what would
// otherwise be several hand-built variants.
func (q *Queries) ListClips(ctx context.Context, arg ListClipsParams) ([]Clip, error) {
	rows, err := q.db.QueryContext(ctx, listClips, arg.PhoneID, arg.State)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Clip{}
	for rows.Next() {
		var i Clip
		if err := rows.Scan(
			&i.ID,
			&i.PhoneID,
			&i.StartedAtMs,
			&i.EndedAtMs,
			&i.SegmentCount,
			&i.SizeBytes,
			&i.State,
			&i.CreatedAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setClipState = `-- name: SetClipState :exec
UPDATE clips SET state = ? WHERE phone_id = ? AND id = ?
`

type SetClipStateParams struct {
	State   string
	PhoneID string
	ID      string
}

func (q *Queries) SetClipState(ctx context.Context, arg SetClipStateParams) error {
	_, err := q.db.ExecContext(ctx, setClipState, arg.State, arg.PhoneID, arg.ID)
	return err
}
