// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package queries

import (
	"context"
)

const getIdentity = `-- name: GetIdentity :one
SELECT public_key, private_key, controller_name FROM identity WHERE id = 1
`

type GetIdentityRow struct {
	PublicKey      []byte
	PrivateKey     []byte
	ControllerName string
}

func (q *Queries) GetIdentity(ctx context.Context) (GetIdentityRow, error) {
	row := q.db.QueryRowContext(ctx, getIdentity)
	var i GetIdentityRow
	err := row.Scan(&i.PublicKey, &i.PrivateKey, &i.ControllerName)
	return i, err
}

const saveIdentity = `-- name: SaveIdentity :exec
INSERT INTO identity (id, public_key, private_key, controller_name) VALUES (1, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET public_key = excluded.public_key, private_key = excluded.private_key, controller_name = excluded.controller_name
`

type SaveIdentityParams struct {
	PublicKey      []byte
	PrivateKey     []byte
	ControllerName string
}

func (q *Queries) SaveIdentity(ctx context.Context, arg SaveIdentityParams) error {
	_, err := q.db.ExecContext(ctx, saveIdentity, arg.PublicKey, arg.PrivateKey, arg.ControllerName)
	return err
}
