// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

type Calibration struct {
	ManufacturerModel string
	SourcePhoneID     string
	CalibratedAtMs    int64
	ResultJson        string
}

type Clip struct {
	ID           string
	PhoneID      string
	StartedAtMs  int64
	EndedAtMs    int64
	SegmentCount int64
	SizeBytes    int64
	State        string
	CreatedAtMs  int64
}

type Identity struct {
	ID             int64
	PublicKey      []byte
	PrivateKey     []byte
	ControllerName string
}

type Phone struct {
	ID           string
	Name         string
	BaseUrl      string
	Token        string
	Manufacturer string
	Model        string
	LastSeenMs   int64
	SyncCursorMs int64
	CreatedAtMs  int64
}

type Segment struct {
	PhoneID       string
	Filename      string
	ClipID        string
	LocalPath     string
	ThumbnailPath string
	CreatedAtMs   int64
	DurationMs    int64
	EndMs         int64
	SizeBytes     int64
	Width         int64
	Height        int64
}
