// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: phones.sql

package queries

import (
	"context"
)

const advanceSyncCursor = `-- name: AdvanceSyncCursor :exec
UPDATE phones SET sync_cursor_ms = ? WHERE id = ?
`

type AdvanceSyncCursorParams struct {
	SyncCursorMs int64
	ID           string
}

func (q *Queries) AdvanceSyncCursor(ctx context.Context, arg AdvanceSyncCursorParams) error {
	_, err := q.db.ExecContext(ctx, advanceSyncCursor, arg.SyncCursorMs, arg.ID)
	return err
}

const deletePhone = `-- name: DeletePhone :exec
DELETE FROM phones WHERE id = ?
`

func (q *Queries) DeletePhone(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePhone, id)
	return err
}

const getPhone = `-- name: GetPhone :one
SELECT id, name, base_url, token, manufacturer, model, last_seen_ms, sync_cursor_ms, created_at_ms
FROM phones WHERE id = ?
`

func (q *Queries) GetPhone(ctx context.Context, id string) (Phone, error) {
	row := q.db.QueryRowContext(ctx, getPhone, id)
	var i Phone
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.Token,
		&i.Manufacturer,
		&i.Model,
		&i.LastSeenMs,
		&i.SyncCursorMs,
		&i.CreatedAtMs,
	)
	return i, err
}

const insertPhone = `-- name: InsertPhone :exec
INSERT INTO phones (id, name, base_url, token, manufacturer, model, last_seen_ms, sync_cursor_ms, created_at_ms)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertPhoneParams struct {
	ID           string
	Name         string
	BaseUrl      string
	Token        string
	Manufacturer string
	Model        string
	LastSeenMs   int64
	SyncCursorMs int64
	CreatedAtMs  int64
}

func (q *Queries) InsertPhone(ctx context.Context, arg InsertPhoneParams) error {
	_, err := q.db.ExecContext(ctx, insertPhone,
		arg.ID,
		arg.Name,
		arg.BaseUrl,
		arg.Token,
		arg.Manufacturer,
		arg.Model,
		arg.LastSeenMs,
		arg.SyncCursorMs,
		arg.CreatedAtMs,
	)
	return err
}

const listPhones = `-- name: ListPhones :many
SELECT id, name, base_url, token, manufacturer, model, last_seen_ms, sync_cursor_ms, created_at_ms
FROM phones ORDER BY created_at_ms ASC
`

func (q *Queries) ListPhones(ctx context.Context) ([]Phone, error) {
	rows, err := q.db.QueryContext(ctx, listPhones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Phone{}
	for rows.Next() {
		var i Phone
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseUrl,
			&i.Token,
			&i.Manufacturer,
			&i.Model,
			&i.LastSeenMs,
			&i.SyncCursorMs,
			&i.CreatedAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePhoneLastSeen = `-- name: UpdatePhoneLastSeen :exec
UPDATE phones SET last_seen_ms = ? WHERE id = ?
`

type UpdatePhoneLastSeenParams struct {
	LastSeenMs int64
	ID         string
}

func (q *Queries) UpdatePhoneLastSeen(ctx context.Context, arg UpdatePhoneLastSeenParams) error {
	_, err := q.db.ExecContext(ctx, updatePhoneLastSeen, arg.LastSeenMs, arg.ID)
	return err
}

const updatePhoneName = `-- name: UpdatePhoneName :exec
UPDATE phones SET name = ? WHERE id = ?
`

type UpdatePhoneNameParams struct {
	Name string
	ID   string
}

func (q *Queries) UpdatePhoneName(ctx context.Context, arg UpdatePhoneNameParams) error {
	_, err := q.db.ExecContext(ctx, updatePhoneName, arg.Name, arg.ID)
	return err
}
