// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: segments.sql

package queries

import (
	"context"
)

const deleteSegment = `-- name: DeleteSegment :exec
DELETE FROM segments WHERE phone_id = ? AND filename = ?
`

type DeleteSegmentParams struct {
	PhoneID  string
	Filename string
}

func (q *Queries) DeleteSegment(ctx context.Context, arg DeleteSegmentParams) error {
	_, err := q.db.ExecContext(ctx, deleteSegment, arg.PhoneID, arg.Filename)
	return err
}

const listSegmentsForClip = `-- name: ListSegmentsForClip :many
SELECT phone_id, filename, clip_id, local_path, thumbnail_path, created_at_ms, duration_ms, end_ms, size_bytes, width, height
FROM segments WHERE clip_id = ? ORDER BY created_at_ms ASC
`

func (q *Queries) ListSegmentsForClip(ctx context.Context, clipID string) ([]Segment, error) {
	rows, err := q.db.QueryContext(ctx, listSegmentsForClip, clipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Segment{}
	for rows.Next() {
		var i Segment
		if err := rows.Scan(
			&i.PhoneID,
			&i.Filename,
			&i.ClipID,
			&i.LocalPath,
			&i.ThumbnailPath,
			&i.CreatedAtMs,
			&i.DurationMs,
			&i.EndMs,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSegmentsWithAbsoluteArchivePaths = `-- name: ListSegmentsWithAbsoluteArchivePaths :many
SELECT phone_id, filename, local_path, thumbnail_path
FROM segments
WHERE instr(local_path, 'panopticon-archive') > 0 OR instr(thumbnail_path, 'panopticon-archive') > 0
`

type ListSegmentsWithAbsoluteArchivePathsRow struct {
	PhoneID       string
	Filename      string
	LocalPath     string
	ThumbnailPath string
}

// Rows written before archive paths were stored relative (see RelativizeArchivePaths) - every
// absolute archive path runs through the archive directory's name.
func (q *Queries) ListSegmentsWithAbsoluteArchivePaths(ctx context.Context) ([]ListSegmentsWithAbsoluteArchivePathsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSegmentsWithAbsoluteArchivePaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSegmentsWithAbsoluteArchivePathsRow{}
	for rows.Next() {
		var i ListSegmentsWithAbsoluteArchivePathsRow
		if err := rows.Scan(
			&i.PhoneID,
			&i.Filename,
			&i.LocalPath,
			&i.ThumbnailPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnassignedSegments = `-- name: ListUnassignedSegments :many
SELECT phone_id, filename, clip_id, local_path, thumbnail_path, created_at_ms, duration_ms, end_ms, size_bytes, width, height
FROM segments WHERE clip_id = '' ORDER BY phone_id ASC, created_at_ms ASC
`

func (q *Queries) ListUnassignedSegments(ctx context.Context) ([]Segment, error) {
	rows, err := q.db.QueryContext(ctx, listUnassignedSegments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Segment{}
	for rows.Next() {
		var i Segment
		if err := rows.Scan(
			&i.PhoneID,
			&i.Filename,
			&i.ClipID,
			&i.LocalPath,
			&i.ThumbnailPath,
			&i.CreatedAtMs,
			&i.DurationMs,
			&i.EndMs,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const segmentExists = `-- name: SegmentExists :one
SELECT COUNT(1) FROM segments WHERE phone_id = ? AND filename = ?
`

type SegmentExistsParams struct {
	PhoneID  string
	Filename string
}

func (q *Queries) SegmentExists(ctx context.Context, arg SegmentExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, segmentExists, arg.PhoneID, arg.Filename)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const setSegmentClip = `-- name: SetSegmentClip :exec
UPDATE segments SET clip_id = ? WHERE phone_id = ? AND filename = ?
`

type SetSegmentClipParams struct {
	ClipID   string
	PhoneID  string
	Filename string
}

func (q *Queries) SetSegmentClip(ctx context.Context, arg SetSegmentClipParams) error {
	_, err := q.db.ExecContext(ctx, setSegmentClip, arg.ClipID, arg.PhoneID, arg.Filename)
	return err
}

const setSegmentPaths = `-- name: SetSegmentPaths :exec
UPDATE segments SET local_path = ?, thumbnail_path = ? WHERE phone_id = ? AND filename = ?
`

type SetSegmentPathsParams struct {
	LocalPath     string
	ThumbnailPath string
	PhoneID       string
	Filename      string
}

func (q *Queries) SetSegmentPaths(ctx context.Context, arg SetSegmentPathsParams) error {
	_, err := q.db.ExecContext(ctx, setSegmentPaths,
		arg.LocalPath,
		arg.ThumbnailPath,
		arg.PhoneID,
		arg.Filename,
	)
	return err
}

const upsertSegment = `-- name: UpsertSegment :exec
INSERT INTO segments (phone_id, filename, clip_id, local_path, thumbnail_path, created_at_ms, duration_ms, end_ms, size_bytes, width, height)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(phone_id, filename) DO NOTHING
`

type UpsertSegmentParams struct {
	PhoneID       string
	Filename      string
	ClipID        string
	LocalPath     string
	ThumbnailPath string
	CreatedAtMs   int64
	DurationMs    int64
	EndMs         int64
	SizeBytes     int64
	Width         int64
	Height        int64
}

func (q *Queries) UpsertSegment(ctx context.Context, arg UpsertSegmentParams) error {
	_, err := q.db.ExecContext(ctx, upsertSegment,
		arg.PhoneID,
		arg.Filename,
		arg.ClipID,
		arg.LocalPath,
		arg.ThumbnailPath,
		arg.CreatedAtMs,
		arg.DurationMs,
		arg.EndMs,
		arg.SizeBytes,
		arg.Width,
		arg.Height,
	)
	return err
}
