// Thin typed wrapper around the generated Wails bindings. Don't hand-edit
// anything under generated/ — it's regenerated by `wails build` / `wails dev`.
// This module just re-exports the bound functions and their model types
// under names the rest of the app imports from, so a binding-shape change
// only needs a fix here (and wherever it flows through) rather than a
// search-and-replace of relative generated/wailsjs import paths across screens.

export {
  ListPhones,
  ParseInviteURL,
  AddPhone,
  GetPhoneDetail,
  ListClips,
  ListTrash,
  TrashClip,
  RestoreClip,
  DeleteClipPermanently,
  EmptyTrash,
  StartCalibration,
  GetCalibrationProgress,
  CancelCalibration,
  SetConfig,
  SetRecording,
  StartLivePreview,
  StopLivePreview,
  UnpairPhone,
  ForceUnpairPhone,
  ListCameras,
  SetActiveCamera,
  GetCameraControls,
  SetCameraControls,
  ComputeEffectiveRect,
} from '../generated/wailsjs/go/main/App';

import type { main, phoneapi, calibration } from '../generated/wailsjs/go/models';

export type PhoneView = main.PhoneView;
export type AddPhoneResult = main.AddPhoneResult;
export type ClipView = main.ClipView;
export type SegmentView = main.SegmentView;
export type ParsedInvite = main.ParsedInvite;
export type PhoneDetailView = main.PhoneDetailView;
export type PhoneApiConfig = phoneapi.Config;
export type PhoneApiConfigPatch = phoneapi.ConfigPatch;
export type PhoneApiStatus = phoneapi.Status;
export type ConfigResult = main.ConfigResult;
export type CalibrationView = calibration.View;
export type CalibrationStartResult = main.CalibrationStartResult;
export type CalibrationProgressResult = main.CalibrationProgressResult;
export type LivePreviewResult = main.LivePreviewResult;
export type CalibrationProgress = phoneapi.CalibrationProgress;
export type UnpairResult = main.UnpairResult;
export type CamerasResult = main.CamerasResult;
export type CameraActionResult = main.CameraActionResult;
export type CameraControlsView = main.CameraControlsView;
export type CameraInfo = phoneapi.CameraInfo;
export type CameraCapabilities = phoneapi.CameraCapabilities;
export type CameraStateResponse = phoneapi.CameraStateResponse;
export type CameraControlKeys = phoneapi.CameraControlKeys;
export type EffectiveRectResult = calibration.EffectiveRectResult;
export type RectNorm = phoneapi.RectNorm;
