// Thin typed wrapper around the generated Wails bindings. Don't hand-edit
// anything under generated/ — it's regenerated by `wails build` / `wails dev`.
// This module just re-exports the bound functions and their model types
// under names the rest of the app imports from, so a binding-shape change
// only needs a fix here (and wherever it flows through) rather than a
// search-and-replace of relative generated/wailsjs import paths across screens.

export {
  ListPhones,
  ParseInviteURL,
  AddPhone,
  GetPhoneDetail,
  ListClips,
  ListTrash,
  TrashClip,
  RestoreClip,
  DeleteClipPermanently,
  EmptyTrash,
} from '../generated/wailsjs/go/main/App';

import type { main, phoneapi } from '../generated/wailsjs/go/models';

export type PhoneView = main.PhoneView;
export type AddPhoneResult = main.AddPhoneResult;
export type ClipView = main.ClipView;
export type ParsedInvite = main.ParsedInvite;
export type PhoneDetailView = main.PhoneDetailView;
export type PhoneApiConfig = phoneapi.Config;
export type PhoneApiStatus = phoneapi.Status;
